### ISSUE TITLE
 Practica 5 Diseño de control personalizado

### ISSUE THREAD

**Issue by EvelynLopezz** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-EvelynLopezz#2]
[FormularioSugey.zip](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-EvelynLopezz/files/8337631/FormularioSugey.zip)
[Practica 5 Diseño de control personalizado.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-EvelynLopezz/files/8337638/Practica.5.Diseno.de.control.personalizado.pdf)

**Comment by josealfredo79** [comment]
Falta la calificación...

**Comment by bg55-a** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
